# Spring boot application
server:
  port: 8081
  servlet:
    context-path: /uservice

dubbo:
  application:
    name: user-service
  registry:
    client: curator  #可选zkclient，默认curator
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 12345
#  scan:
#    base-packages: com.xianyuli.dubbo.bootdubboapi.service


# datasource config
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-user.sql
    data: classpath:db/user.sql
    url: jdbc:h2:file:~/.h2/user;AUTO_SERVER=TRUE
    username: root
    password: 1234
  h2:
    console:
      enabled: true #开启web console功能

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug